spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        session_factory.interceptor: pl.databucket.tenant.EntityInterceptor
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    initialization-mode: always

logging:
  level:
    root: info
    org.springframework.web: error
    org.hibernate: error
    pl.databucket.service.data.DataService: error